name: Unswash E2E on Chrome

on: [push]
# on:
#   push:
#     branches:
#       - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      # - run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: ./cypress
          browser: chrome
          command: yarn run cypress run --headless --browser chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
