name: Unswash E2E on Chrome

# on: [push]
on:
  push:
    branches:
      - cypress-testing

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install Dependencies
          run: npm install --force
        - name: Cypress Run
          uses: cypress-io/github-action@v6
          with:
              install: npm ci --force
              browser: chrome
              build: npm run build
              start: npm start
              command: npx cypress run --e2e --browser chrome --headless
              wait-on: 'http://localhost:3000'
          
